Python_Class/Django/login_with_multiapp/apps/posts/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.wall, name='the_wall'),
]

Python_Class/Django/login_with_multiapp/login_registration/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^', include('apps.log_reg.urls', namespace = 'login_namesp')),
    url(r'^', include('apps.posts.urls', namespace = 'posts_namesp'))
]

# invalid syntax error usually means you forgot to put in the second closing parentheses!
# namespace is how we will refer to apps when we have multiple apps!

Python_Class/Django/login_with_multiapp/apps/posts/models.py
from __future__ import unicode_literals

from django.db import models
from ..log_reg.models import User #don't forget to import our first app's model! Put this in both!
#from ..firstApp.models import class

# Create your models here.
class PostManager(models.Manager):
    def post_post(self):
        pass




#make your POST models!
class Post(models.Model):
    content = models.TextField()
    user = models.ForeignKey(User, related_name = "posted_by")
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    objects = PostManager()
    #since UserManager is inhereted from our User class, we will have access to 

#we are going to make a third app for our comments

Python_Class/Django/login_with_multiapp/apps/posts/views.py
from django.shortcuts import render
from django.contrib import messages

# Create your views here.
def wall(request):
   #will add context
   print ("hello")*50
   return render(request, 'posts/wall.html')
    

Python_Class/Django/login_with_multiapp/apps/posts/templates/posts/posts.html
<html>

<head>
    <title>Login & Registration</title>
    {% load staticfiles %}
	<link rel="stylesheet" href="{% static '/posts/css/stylesheet.css' %}" media="screen" charset="utf-8">
</head>

<body>
    <div class="wrapper">
        <div class="header">
            <h1>The Message Wall</h1>
        </div>

        <div class="error">
            <ul>
            {% for idx in messages %}
                <li>{{ idx}}</li>
            {% endfor %}
            </ul>
        </div>
        
        <div class="contentBox">
                <form class="boxes" action= '{% url "posts_namesp:create_post" %}' method='POST'>
                    {% csrf_token %} 
                    <h2>Write a Message</h2>
                    <textarea rows="10" cols="50"></textarea>
                    <input type="submit" value="Post!">
                </form>
                
        </div>
       
   </div>
    
</body>

</html>

Python_Class/Django/login_with_multiapp/apps/posts/templates/posts/wall.html
<html>

<head>
    <title>Login & Registration</title>
    {% load staticfiles %}
	<link rel="stylesheet" href="{% static '/posts/css/stylesheet.css' %}" media="screen" charset="utf-8">
</head>

<body>
    <div class="wrapper">
        <div class="header">
            <h1>The Message Wall</h1>
        </div>

        <!--<div class="error">
            <ul>
            {% if idx in messages %}
                <li>{{ idx}}</li>
            {% endif %}
            </ul>
        </div>-->
        
        <!--<div class="contentBox">
                <form class="boxes" action= '{% url "posts_namesp:the_wall" %}' method='POST'>
                    {% csrf_token %} 
                    <h2>Write a Message</h2>
                    <textarea rows="10" cols="50"></textarea>
                    <input type="submit" value="Post!">
                </form>
                
        </div>-->
       
   </div>
    
</body>

</html>